export const Nec_Code_List = [
  "0000: Generic programmes and qualifications not further defined",
  "0011: Basic programmes and qualifications",
  "0021: Literacy and numeracy",
  "0031: Personal skills",
  "0099: Generic programmes and qualifications not elsewhere classified",
  "0110: Education not further defined",
  "0111: Education science",
  "0112: Training for pre-school teachers",
  "0113: Educator training without subject specialisation",
  "0114: Educator training with subject specialisation",
  "0119: Programmes and qualifications involving education not elsewhere classified",
  "0188: Inter-disciplinary programmes and qualifications involving education",
  "0200: Arts and humanities not further defined",
  "0210: Arts not further defined",
  "0211: Audio-visual techniques and media production",
  "0212: Fashion, interior and industrial design",
  "0213: Fine arts",
  "0214: Craft skills",
  "0215: Music and performing arts",
  "0216: Film, television and screen studies",
  "0219: Arts not elsewhere classified",
  "0220: Humanities (except languages) not further defined",
  "0221: Religion and theology",
  "0222: History and archaeology",
  "0223: Philosophy and ethics",
  "0224: Islamic studies",
  "0229: Humanities (except languages) not elsewhere classified",
  "0230: Languages not further defined",
  "0231: Language acquisition",
  "0232: Literature and linguistics",
  "0233: National language",
  "0239: Languages not elsewhere classified",
  "0288: Inter-disciplinary programmes and qualifications involving arts and humanities",
  "0299: Arts and humanities not elsewhere classified",
  "0300: Social sciences, journalism and information not further defined",
  "0310: Social and behavioural sciences not further defined",
  "0311: Economics",
  "0312: Political sciences and public policy",
  "0313: Psychology",
  "0314: Sociology and cultural studies",
  "0319: Social and behavioural sciences not elsewhere classified",
  "0320: Journalism, information and communication not further defined",
  "0321: Journalism and reporting",
  "0322: Library, information and archival studies",
  "0323: Media and communication",
  "0329: Journalism, information and communication not elsewhere classified",
  "0388: Inter-disciplinary programmes and qualifications involving social sciences, journalism and information",
  "0399: Social sciences, journalism and information not elsewhere classified",
  "0400: Business, administration and law not further defined",
  "0410: Business and administration not further defined",
  "0411: Accounting, auditing and taxation",
  "0412: Finance, banking and insurance",
  "0413: Islamic banking and finance",
  "0414: Management and administration",
  "0415: Marketing and advertising",
  "0416: Secretarial and office studies",
  "0417: Work skills",
  "0419: Business and administration not elsewhere classified",
  "0421: Law",
  "0488: Inter-disciplinary programmes and qualifications involving business, administration and law",
  "0499: Business, administration and law not elsewhere classified",
  "0500: Natural sciences, mathematics and statistics not further defined",
  "0510: Biological and related sciences not further defined",
  "0511: Biology",
  "0512: Biochemistry",
  "0519: Biological and related sciences not elsewhere classified",
  "0520: Environment not further defined",
  "0521: Environmental sciences",
  "0522: Natural environments and wildlife",
  "0529: Environment not elsewhere classified",
  "0530: Physical sciences not further defined",
  "0531: Chemistry",
  "0532: Earth sciences",
  "0533: Physics",
  "0539: Physical sciences not elsewhere classified",
  "0540: Mathematics and statistics not further defined",
  "0541: Mathematics",
  "0542: Statistics",
  "0588: Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics",
  "0599: Natural sciences, mathematics and statistics not elsewhere classified",
  "0610: Information and communication technologies (ICTs) not further defined",
  "0611: Information technology and information system",
  "0612: Software engineering",
  "0613: Computer science",
  "0614: Computer use",
  "0619: Information and communication technologies (ICTs) not elsewhere classified",
  "0688: Inter-disciplinary programmes and qualifications involving information and communication technologies",
  "0700: Engineering, manufacturing and construction not further defined",
  "0710: Engineering and engineering trades not further defined",
  "0711: Chemical engineering and processes",
  "0712: Electricity and energy",
  "0713: Electronics and automation",
  "0714: Mechanics and metal trades",
  "0715: Motor vehicles, ships and aircraft",
  "0716: Civil engineering",
  "0717: Environmental protection technology",
  "0719: Engineering and engineering trades not elsewhere classified",
  "0720: Manufacturing and processing not further defined",
  "0721: Food processing",
  "0722: Materials (glass, paper, plastic and wood)",
  "0723: Textiles (clothes, footwear and leather)",
  "0724: Mining and extraction",
  "0729: Manufacturing and processing not elsewhere classified",
  "0730: Architecture, surveying and town planning not further defined",
  "0731: Architecture",
  "0732: Urban and regional planning",
  "0733: Building and construction",
  "0734: Surveying",
  "0741: Engineering technology",
  "0788: Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction",
  "0799: Engineering, manufacturing and construction not elsewhere classified",
  "0800: Agriculture, forestry, fisheries and veterinary not further defined",
  "0810: Agriculture not further defined",
  "0811: Crop and livestock production",
  "0812: Horticulture",
  "0819: Agriculture not elsewhere classified",
  "0821: Forestry",
  "0831: Fisheries",
  "0841: Veterinary",
  "0888: Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary",
  "0899: Agriculture, forestry, fisheries and veterinary not elsewhere classified",
  "0900: Health and welfare not further defined",
  "0910: Health not further defined",
  "0911: Dental studies",
  "0912: Medicine",
  "0913: Nursing, midwifery and medical assistance",
  "0914: Medical diagnostic and treatment technology",
  "0915: Therapy and rehabilitation",
  "0916: Pharmacy",
  "0917: Traditional and complementary medicine and therapy",
  "0919: Health not elsewhere classified",
  "0920: Welfare not further defined",
  "0921: Care of elderly and of disabled adults",
  "0922: Child care and youth services",
  "0923: Social work and counselling",
  "0929: Welfare not elsewhere classified",
  "0988: Inter-disciplinary programmes and qualifications involving health and welfare",
  "0999: Health and welfare not elsewhere classified",
  "1000: Services not further defined",
  "1010: Personal services not further defined",
  "1011: Domestic services",
  "1012: Hair and beauty services",
  "1013: Hotel, restaurants and catering",
  "1014: Sports",
  "1015: Travel, tourism and leisure",
  "1019: Personal services not elsewhere classified",
  "1020: Hygiene and occupational health services not further defined",
  "1021: Community sanitation",
  "1022: Occupational health and safety",
  "1029: Hygiene and occupational health services not elsewhere classified",
  "1030: Security services not further defined",
  "1031: Military and defence",
  "1032: Protection of persons and property",
  "1039: Security services not elsewhere classified",
  "1041: Transport services",
  "1088: Inter-disciplinary programmes and qualifications involving services",
  "1099: Services not elsewhere classified",
  "9999: Field unknown",
];

export const mod_penawaran = [
  "Kerja Kursus",
  "Mod Industri",
  "Penyelidikan",
  "Mod Campuran",
];

export const fakulti_List = [
  "Fakulti Sains Komputer dan Matematik (FSKM)",
  "Fakulti Teknologi Kejuruteraan Kelautan (FTKK)",
  "Fakulti Sains dan Sekitaran Marin (FSSM)",
  "Fakulti Perikanan dan Sains Makanan (FPSM)",
  "Fakulti Pengajian Maritim  (FPM)",
  "Fakulti Perniagaan Ekonomi dan Pembangunan Sosial (FPEPS)",
];

export const struktur_program = [
  "Major",
  "Major dengan Pengkhususan",
  "Major-minor",
  "Dwimajor",
  "Dwi Ijazah",
  "Dual Ijazah",
  "Ijazah Bersama",
];

export const bentuk_kerjasama = [
  "Dual Ijazah (Dual Degree)",
  "Dwi Ijazah (Double Degree)",
  "Ijazah Bersama (Joint Degree)",
  "Francais (Franchise)",
  "Luar Pesisir (Offshore)",
];
